### ISSUE TITLE
shift causing NoSuchMethodError

### ISSUE THREAD

**Issue by krrr** [scala/scala-continuations#11]
I'm new to scala and discouraged by this problem...Can anyone help me? I have spent a lot of time searching and find this [already fixed](https://issues.scala-lang.org/browse/SI-3107?jql=text%20~%20%22NoSuchMethodError%22):

```
scala> import util.continuations._
scala> reset {shift {k: (String => String) => "BB"}; "AA"}
java.lang.NoSuchMethodError: scala.util.continuations.package$.shift(Lscala/Function1;)Ljava/lang/Object;
  at $anonfun$1.apply(<console>:11)
  at $anonfun$1.apply(<console>:11)
  at scala.util.continuations.package$.reifyR(package.scala:184)
  at scala.util.continuations.package$.reset(package.scala:133)
  ... 33 elided
```
Running Scala version 2.11.6 (Java HotSpot(TM) Client VM, Java 1.8.0_40) on Windows 7. Besides this, I tried to pass -P:continuations:enable to `scala` but always got `[init] error: bad option: -P:continuations:enable`

**Comment by krrr** [comment]
I didn't know one should also use `-Xplugin` to specify plugin jar file, but document said nothing about this...

**Comment by SethTisue** [comment]
de facto doc is http://stackoverflow.com/q/2683195/86485

**Comment by jimka2001** [comment]
I'm having the same problem.   Even when I revert to scala 2.11.6, I still get the errors krrr described.  When I add the -Xpluginsdir flag as described in, http://stackoverflow.com/q/2683195/86485, I get a compiler error:Error:scalac: bad option: '-Xpluginsdir /.../scala/lib/'
