### ISSUE TITLE
Fails to build on 2.12.0-RC1

### ISSUE THREAD

**Issue by danslapman** [scala/scala-continuations#20]
`implicit method defaultExecutionContext is not applicable here because it comes after the application point and it lacks an explicit result type`
https://travis-ci.org/scala/scala-continuations/jobs/159573627

**Comment by SethTisue** [comment]
the changes in [#5141](https://github.com/scala/scala/pull/5141) and
[#5294](https://github.com/scala/scala/pull/5294) commonly cause errors like this on implicits that lack explicitly declared result types. declaring the type is good practice anyway

**Comment by danslapman** [comment]
https://travis-ci.org/scala/scala-continuations/jobs/159716395, can be related to https://github.com/scala/scala-dev/issues/219, will continue my investigation tomorrow

**Comment by danslapman** [comment]
Fixed by #21
