### ISSUE TITLE
be dbuild friendly?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-continuations#23]
I would like to add this repository to the Scala 2.12 community build, but in a community build context, you have to be able to deal with arbitrary Scala versions like `2.12.0-1e81a09-nightly`, not just certain known releases like `2.12.0-RC1`

this is fixable if you rename `plugin/src/main/scala-2.12.0-RC1` to `plugin/src/main/scala-2.12` and use `CrossVersion.partialVersion(scalaVersion.value) match ...` — see non/spire#587 for an example of how the needed changes looked in another project

**Comment by danslapman** [comment]
Will do it today or tomorrow

**Comment by danslapman** [comment]
@SethTisue I adjusted build.sbt as You suggested. Check it out, if it's all fine, i will add release tag to master (I also bumped to 2.12.0-RC2 in this PR)

**Comment by SethTisue** [comment]
thanks — I'll take care of adding scala-continuations to the 2.12 community build soon
