### ISSUE TITLE
Release continuations plugin for 2.12.1

### ISSUE THREAD

**Issue by dotta** [scala/scala-continuations#28]
Hello, I noticed there is currently no release of the continuations plugin for Scala 2.12.1. It'd be great if it could be released.

**Comment by danslapman** [comment]
@dotta surely, will do it this week.

**Comment by dotta** [comment]
Awesome. Thanks!

**Comment by danslapman** [comment]
Sorry for a delay, I just changed employer and had no free time the previous week. Will do it soon.

**Comment by danslapman** [comment]
WIP: #29

**Comment by danslapman** [comment]
`2.11.11`, `2.12.1` & `2.12.2` artifacts are staged to Sonatype. @SethTisue please promote them to maven central.

**Comment by lrytz** [comment]
Nice! I can also do that. The staging repos are

  - https://oss.sonatype.org/content/repositories/orgscala-lang-1408 for `2.12.1`
  - https://oss.sonatype.org/content/repositories/orgscala-lang-1409 for `2.12.2`
  - https://oss.sonatype.org/content/repositories/orgscala-lang-1410 for `2.11.11`
  - https://oss.sonatype.org/content/repositories/orgscala-lang-1411 for `2.13.0-M1`

Would you like to make a quick cross-check if everything looks OK? To me it looks good, I checked a `MANIFEST.MF`, some POMs, etc

**Comment by danslapman** [comment]
Everything looks fine, I also manually checked 2.12.x artifacts in my work projects.

**Comment by lrytz** [comment]
OK, I released the repos. Thanks again!
