### ISSUE TITLE
Scala 2.13 support is missing

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-continuations#37]
seen at https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/919/consoleFull:

```
[scala-continuations] [error] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.9/project-builds/scala-continuations-b6d82c47a2aa68e22085eee21951484d2c3d153c/library/src/test/scala/scala/tools/selectivecps/TestSuite.scala:215: cannot compute type for CPS-transformed function result
[scala-continuations] [error]     test { shift { k: (Int => String) => 9 }; { test3(0); 2 } }
[scala-continuations] [error]                  ^
```

not sure what 2.13 PR might have triggered this, but it must be recent because the project was green as recently as https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/912/consoleFull . the main thing that landed in 2.13 since then was a big merge of many PRs from 2.12.x to 2.13.x (scala/scala#6280)

**Comment by SethTisue** [comment]
I would expect the problem to be reproducible using a 2.13 nightly build (see [instructions](https://stackoverflow.com/questions/40622878/how-do-i-tell-sbt-to-use-a-nightly-build-of-scala-2-11-2-12-or-2-13))

**Comment by SethTisue** [comment]
very likely additional 2.13-related breakage has now accumulated. would someone like to volunteer to take this on?

**Comment by SethTisue** [comment]
#47 drops the 2.13 crossbuild (since 2.13.0-M1 is no longer relevant), but it could be re-added

**Comment by danslapman** [comment]
Being honest, I don't have enough time to support scala-continuations any more :( My previous employer was interested in supporting this plugin, but I changed my job twice since that times...

**Comment by danslapman** [comment]
In fact now we have IndexedContT in scalaz and ContT in cats + unoficial IndexedContT port as alternative to continuations plugin

**Comment by SethTisue** [comment]
> Being honest, I don't have enough time to support scala-continuations any more 

thanks for letting me know! #48 removes you from the readme. thanks for your attention to this over the last few years, it's been appreciated.

**Comment by SethTisue** [comment]
See #49.

I've updated the repo README to say up front that only 2.12 and earlier were ever supported.
