### ISSUE TITLE
new volunteer maintainer wanted

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-continuations#49]
the README also mentions this, since #48 

it's been a while since this repo has seen any activity. it's not clear to me if there are any remaining users.

(if I new volunteer maintainer doesn't appear in the next 6 months, I suggest we archive the repo at that point)

**Comment by Dolu1990** [comment]
I was using it in a important part of a project to get light userspace threads for hardware simulation.
Example : https://spinalhdl.github.io/SpinalDoc-RTD/SpinalHDL/Simulation/examples/uart_decoder.html
Where context switching should go as high than 1-2 Mhz

But the scala-continuations had too many traps and undesired limitations that i had to drop it for raw JVM thread, at the cost of 20 time the performance :(, but a smooth and slow threaded API, and an additional but not as flexible thread-less API.

So, not using it anymore.

Anyway, userspace thread would realy be a usefull thing.

**Comment by Kraks** [comment]
Hi, I'm a graduate student at Purdue University, working with Tiark Rompf. I'm happy to do something for this project, such as adding support for Scala 2.13 (#37). 

Personally, I'm also interested in implementing higher-level delimited control operators (CPS hierarchy) based on this project.

**Comment by adriaanm** [comment]
Great! I've sent you an invite that gives you write access to this repo.

**Comment by SethTisue** [comment]
@kraks welcome! for info on what Scala module maintenance involves, the main source is https://github.com/scala/sbt-scala-module/issues/16

feel free to update the maintenance-status info in the repo README here as you see fit

**Comment by SethTisue** [comment]
also, announcing your intentions on https://contributors.scala-lang.org might drum up some other volunteer assistance, you never know

**Comment by Kraks** [comment]
@SethTisue @adriaanm Thanks for the invitation and pointer!

**Comment by brehar** [comment]
I would also be happy to volunteer to work on this project. If you are still looking for volunteers, let me know!

**Comment by SethTisue** [comment]
> I would also be happy to volunteer to work on this project. If you are still looking for volunteers, let me know!

it's been several months since we've heard from @Kraks, so I'd say yes. (although even if we do hear from @Kraks, presumably he'd welcome your participation regardless!)

what's your motivation, are you interested in tackling the 2.13 work at all, or are you just looking to keep the lights on for Scala <= 2.12?

**Comment by SethTisue** [comment]
For the record, if anyone wants to revive this repo, please inquire on https://contributors.scala-lang.org. (Personally I think any revival attempt should be published under a different org.)
