### ISSUE TITLE
Release continuations for 2.12.8

### ISSUE THREAD

**Issue by jimka2001** [scala/scala-continuations#50]
Would it be possible to publish this library for 2.12.8 ?

**Comment by SethTisue** [comment]
@Kraks if you're interested in tackling this, there's some guidance at https://github.com/scala/sbt-scala-module/issues/16

as a workaround, @jimka2001 I think you've found that using the version built for 2.12.2 actually works okay with 2.12.8?

**Comment by Kraks** [comment]
Thanks @SethTisue, I think I can do that. Before that I just want to double-check: the Github release page contains the release for 2.12.x, although it's been a while but should work for 2.12.8, what I need to do is to publish the plugin to Maven/Sonatype repository (currently it is only published for scala 2.12.2), is that right?

**Comment by SethTisue** [comment]
yes, that's right. back-publishing an existing plugin version for an additional Scala version is done by pushing a specially named tag, as documented at https://github.com/scala/scala-continuations/blob/master/admin/README.md . this will cause Travis-CI to publish artifacts to a Sonatype staging repo; then someone from the Scala team will (on request) release them to Maven Central

**Comment by SethTisue** [comment]
Highly unlikely to ever happen. Archiving the repo.
