### ISSUE TITLE
Very sad to know that it will be unsupported

### ISSUE THREAD

**Issue by iron9light** [scala/scala-continuations#7]
I'm a heavy user of continuation plugin. It's the soul of my own lib [erla](https://github.com/iron9light/erla/blob/akka2.2/src/test/scala/iron9light/util/erla/ErlActorSuite.scala).
erla makes akka Actor with erlang style.

``` scala
    val actorB = system.actorOf(Props(new Actor {
      def receive = {
        case x =>
          sender !("got it", x)
          println("actor B reply " + x)
      }
    }))

    val actorA = system.actorOf(Props(new ErlActor {
      def act() = {
        println("actor A started")
        val msg = "hello"
        import akka.pattern.ask
        val replied = await(actorB ? msg)
        println(replied)
        replied match {
          case ("got it", `msg`) =>
            println("works")
          case x =>
            println("wrong: " + x)
        }
      }
    }).withDispatcher("erla"))
```

Thanks all your works!
I wish I could maintain this amazing plugin, I think there must be some lib/projects need continuation but not just [scala-async](https://github.com/scala/async). But I don't think I have enough skill to do this.
I wish someone could take over it soon.
I love this plugin!

IL

**Comment by MasseGuillaume** [comment]
@iron9light https://github.com/jedesah/computation-expressions
